# @format

version: 2.1

jobs:
  build-and-deploy:
    docker:
      - image: cimg/docker:20.10.24-git
    steps:
      - checkout
      - run:
          name: Login to Docker Hub
          command: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - run:
          name: Build and test
          command: |
            docker build -t llms-txt-generator .
            docker run --rm -e FIRECRAWL_API_KEY=test_key llms-txt-generator python -c "import main; print('Test passed')"
      - run:
          name: Tag and push
          command: |
            docker tag llms-txt-generator $DOCKER_USERNAME/llms-txt-generator:latest
            docker push $DOCKER_USERNAME/llms-txt-generator:latest

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only: main
