# @format

version: 2.1

# The docker orb provides pre-configured environments and commands
orbs:
  docker: circleci/docker@2.4.0

jobs:
  build-and-test:
    docker:
      - image: cimg/docker:20.10.24-git
    steps:
      - checkout
      - run:
          name: Login to Docker Hub
          command: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - run:
          name: Build Docker image
          command: docker build -t llms-txt-generator .
      - run:
          name: Test container startup
          command: |
            docker run -d --name test-container -p 8000:8000 -e FIRECRAWL_API_KEY=test_key llms-txt-generator
            sleep 15
            docker ps | grep test-container | grep healthy
            curl -f http://localhost:8000/ || exit 1
            curl -f http://localhost:8000/docs || exit 1
            docker stop test-container
            docker rm test-container
      - run:
          name: Run Python tests
          command: docker run --rm -e FIRECRAWL_API_KEY=test_key llms-txt-generator python -c "import main; print('Application imports successfully')"
      - run:
          name: Save Docker image to workspace
          command: |
            mkdir -p workspace
            docker save -o workspace/image.tar llms-txt-generator
      - persist_to_workspace:
          root: workspace
          paths:
            - image.tar

  deploy:
    docker:
      - image: cimg/docker:20.10.24-git
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Login to Docker Hub
          command: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - run:
          name: Load and tag Docker image
          command: |
            docker load -i /tmp/workspace/image.tar
            docker tag llms-txt-generator $DOCKER_USERNAME/llms-txt-generator:latest
            docker tag llms-txt-generator $DOCKER_USERNAME/llms-txt-generator:$CIRCLE_SHA1
      - run:
          name: Push to Docker Hub
          command: |
            docker push $DOCKER_USERNAME/llms-txt-generator:latest
            docker push $DOCKER_USERNAME/llms-txt-generator:$CIRCLE_SHA1

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: main
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only: main
