# @format

version: 2.1

# The docker orb is no longer strictly needed but is good practice to keep.
orbs:
  docker: circleci/docker@2.4.0

jobs:
  build-and-test:
    # Use a basic, general-purpose CircleCI image.
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      # Activate a remote Docker environment. This is the key step.
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Login to Docker Hub
          command: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - run:
          name: Build Docker image
          command: docker build -t llms-txt-generator .
      - run:
          name: Test container startup
          command: |
            # 1. Create a dedicated network for our containers to communicate on.
            docker network create test-net

            # 2. Run the application container on the new network.
            #    Port mapping (-p) is no longer needed as we connect directly via the network.
            docker run -d --name test-container --network test-net -e FIRECRAWL_API_KEY=test_key llms-txt-generator

            echo "Waiting for container to initialize..."
            sleep 15

            echo "--- Container Logs ---"
            docker logs test-container
            echo "----------------------"

            echo "Testing container health and API endpoints..."
            docker ps | grep test-container | grep healthy

            # 3. Connect to the container by its name, not localhost.
            curl -f --retry 5 --retry-delay 3 http://test-container:8000/ || exit 1
            curl -f http://test-container:8000/docs || exit 1

            # 4. Clean up the container and the network.
            docker stop test-container
            docker rm test-container
            docker network rm test-net
      - run:
          name: Run Python tests
          command: docker run --rm -e FIRECRAWL_API_KEY=test_key llms-txt-generator python -c "import main; print('Application imports successfully')"
      - run:
          name: Save Docker image to workspace
          command: |
            mkdir -p workspace
            docker save -o workspace/image.tar llms-txt-generator
      - persist_to_workspace:
          root: workspace
          paths:
            - image.tar

  deploy:
    # Use the same basic image for consistency.
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      # Activate the remote Docker environment here as well.
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Login to Docker Hub
          command: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - run:
          name: Load and tag Docker image
          command: |
            docker load -i /tmp/workspace/image.tar
            docker tag llms-txt-generator $DOCKER_USERNAME/$IMAGE_NAME:latest
            docker tag llms-txt-generator $DOCKER_USERNAME/$IMAGE_NAME:$CIRCLE_SHA1
      - run:
          name: Push to Docker Hub
          command: |
            docker push $DOCKER_USERNAME/$IMAGE_NAME:latest
            docker push $DOCKER_USERNAME/$IMAGE_NAME:$CIRCLE_SHA1

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: main
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only: main
