# @format

version: 2.1

jobs:
  build-and-test:
    # 1. Start in a basic, universally available environment that will not be rate-limited.
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      # 2. Activate a dedicated, remote Docker engine for this job.
      #    This is the official, recommended way to run Docker commands.
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Login to Docker Hub
          command: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - run:
          name: Build Docker image
          command: docker build -t llms-txt-generator .
      - run:
          name: Test container startup and networking
          command: |
            docker network create test-net
            docker run -d --name test-container --network test-net -e FIRECRAWL_API_KEY=test_key llms-txt-generator
            echo "Waiting for container to become healthy..."
            sleep 15
            echo "Testing API endpoints from within the network..."
            docker run --network test-net --rm alpine/curl -f --retry 5 --retry-delay 3 http://test-container:8000/
            docker stop test-container
            docker rm test-container
            docker network rm test-net
      - run:
          name: Save Docker image to workspace
          command: |
            mkdir -p workspace
            docker save -o workspace/image.tar llms-txt-generator
      - persist_to_workspace:
          root: workspace
          paths:
            - image.tar

  deploy:
    # Use the same basic, reliable environment.
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      # Activate the dedicated Docker engine here as well.
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Login to Docker Hub
          command: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - run:
          name: Load and tag Docker image
          command: |
            docker load -i /tmp/workspace/image.tar
            docker tag llms-txt-generator $DOCKER_USERNAME/$IMAGE_NAME:latest
            docker tag llms-txt-generator $DOCKER_USERNAME/$IMAGE_NAME:$CIRCLE_SHA1
      - run:
          name: Push to Docker Hub
          command: |
            docker push $DOCKER_USERNAME/$IMAGE_NAME:latest
            docker push $DOCKER_USERNAME/$IMAGE_NAME:$CIRCLE_SHA1

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: main
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only: main
